tasks:
  - init: |
      (
        #To install streamlit
        sudo pip3 install streamlit
        #To install MQTT service
        sudo apt install -y mosquitto
        sudo apt install mosquitto-clients
        sudo service mosquitto start
        sudo service mosquitto status
        #To install Paho-MQTT
        sudo pip3 install paho-mqtt
        git clone https://github.com/eclipse/paho.mqtt.python.git
        cd paho.mqtt.python
        python setup.py install
        #To instal pyAudio
        sudo apt install build-essential portaudio19-dev python3.10-dev
        sudo apt-get install libasound-dev portaudio19-dev libportaudio2 libportaudiocpp0
        sudo apt-get install ffmpeg libav-tools
        pip install pyaudio
        
        #extensions for python code
        pip3 install -r requirements.txt
        sudo pip install --upgrade librosa
        sudo pip install --upgrade matplotlib
      )


github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to true)
    addComment: true
    # add a "Review in Gitpod" button to pull requests (defaults to false)
    addBadge: false
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: prebuilt-in-gitpod
